### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [zoombacoin/zoomba#2]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      zoomba/LICENSE

**Comment by zoombacoin** [comment]
Hello, We would like to correct and resolve asap. Can you please direct me as to how to properly correct missing information? 
Regards,
Zoomba Team

**Comment by Iconoclasta** [comment]
Hey, no problem:
Check [Pull 4](https://github.com/zoombacoin/zoomba/pull/4)
:+1:

**Comment by zoombacoin** [comment]
Im sorry, Another person set up Zoomba Github. I am not familiar with it. Am I suppose to click the Merge Pull Request? And what will this do? will it correct the issue? Thank you for your help in resolving

**Comment by zoombacoin** [comment]
Is this to delete the license? Dont I need to edit to include PIVX developers? I really appreciate your help, as I am not familiar but want to make sure everything is correct. Thanks again.

**Comment by Iconoclasta** [comment]
Hey, just click "Merge Pull Request" and you'll be good. 
You can see you already have a license with zoomba, pivx, dash and bitcoin included: It's [COPYING](https://github.com/zoombacoin/zoomba/blob/master/COPYING) and that should be the ONLY license in your github.

Thanks for the collaboration!

**Comment by zoombacoin** [comment]
Ok, Thank you for your help. Merge Pull Request completed. Thanks again for helping, and sorry for not being correct. Regards

**Comment by Myke500** [comment]
Does this close the issue?

**Comment by Iconoclasta** [comment]
Sure thing. Thanks for the collaboration. Closing this issue now.
